### PR TITLE
Update stephencwelch.yaml

### PR DESCRIPTION
**Pull request by stephencwelch**
> Pull Requests will be used to communicate with the community and update the conference website.  Use speaker templates to get speaker information.

Dear @username, we are thrilled you are going to participate in JupyterDay Atlanta.  We are going to need a little bit of information about you.  Once we recieve all of your information and close this pull request; the conference website will be updated with your information.

> PROTIP: You can respond directly to this pull request or [drag and drop attachments into the response](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).  We will manually update your conference data.

### CODE REVIEW

**Comment by bollwyvl** [comment]
We'll probably treat the long fields as a limited subset of markdown. We can pretty up your links in post :) Thanks for playing along!

**Comment by stephencwelch** [comment]
Ok, great. Yeah, I wasn't sure what kind of formatting you needed.

**Comment by bollwyvl** [comment]
Well, haven't written the code yet :) It will probably all jekylly, which is @tonyfast's 👜

**Comment by stephencwelch** [comment]
Excellent.

**Comment by tonyfast** [comment]
@stephencwelch your pull request has been merged and accepted. Thank you so much giving a talk at JupyterDay.  We are delighted that everyone will get to hear the ["Bob Ross of Machine Learning"](https://twitter.com/stephencwelch/status/709870101349146624) present!

Would you like a repository in this organization to host any materials?

**Comment by stephencwelch** [comment]
Hahaha word. I can't think of any materials I'll need to be hosted presently, I'll let you know if anything changes. Looking forward to it!

**Pull request closed without merging**
